name: Build Storybook

run-name: Build Storybook

env:
  USER_EMAIL: ${{ secrets.USER_EMAIL }}

on: [push]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn build-storybook
      - run: git add .
      - run: git config --global user.email $USER_EMAIL
      - run: git commit -m "docs(build):make the build of storybook"
      - run: git push origin main
